/* Additional record code for pump_v3_basicCold_t generated by the OpenModelica Compiler OpenModelica v1.26.1 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "pump_v3_basicCold_t_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc_added 1
const char* IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc__fields[3] = {"n","V_flow","dp"};
struct record_description IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc = {
  "IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal", /* package_record__X */
  "IDEAS.Fluid.Movers.BaseClasses.Characteristics.flowParametersInternal", /* package.record_X */
  IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc__fields
};

void IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct_p(threadData_t *threadData, void* v_ths ) {
  IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* ths = (IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_ths);
  // ths->_n has no default value.
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)ths->_n); // ths->_V_flow has no default value.
  alloc_real_array(&(ths->_dp), 1, (_index_t)ths->_n); // ths->_dp has no default value.
}
void IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_integer in_n, real_array in_V_flow, real_array in_dp) {
  IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* dst = (IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_dst);
  dst->_n = in_n;
  dst->_V_flow = in_V_flow;
  dst->_dp = in_dp;
}

void IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p(void* v_src, void* v_dst) {
  IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* src = (IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_src);
  IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* dst = (IDEAS_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_dst);
  dst->_n = src->_n;
  real_array_copy_data(src->_V_flow, dst->_V_flow);
  real_array_copy_data(src->_dp, dst->_dp);
}


#define IDEAS_Fluid_Movers_BaseClasses_Euler_peak__desc_added 1
const char* IDEAS_Fluid_Movers_BaseClasses_Euler_peak__desc__fields[3] = {"V_flow","dp","eta"};
struct record_description IDEAS_Fluid_Movers_BaseClasses_Euler_peak__desc = {
  "IDEAS_Fluid_Movers_BaseClasses_Euler_peak", /* package_record__X */
  "IDEAS.Fluid.Movers.BaseClasses.Euler.peak", /* package.record_X */
  IDEAS_Fluid_Movers_BaseClasses_Euler_peak__desc__fields
};

void IDEAS_Fluid_Movers_BaseClasses_Euler_peak_construct_p(threadData_t *threadData, void* v_ths ) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_peak* ths = (IDEAS_Fluid_Movers_BaseClasses_Euler_peak*)(v_ths);
  // ths->_V_flow has no default value.
  // ths->_dp has no default value.
  ths->_eta = 0.7;
}
void IDEAS_Fluid_Movers_BaseClasses_Euler_peak_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_V_flow, modelica_real in_dp, modelica_real in_eta) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_peak* dst = (IDEAS_Fluid_Movers_BaseClasses_Euler_peak*)(v_dst);
  dst->_V_flow = in_V_flow;
  dst->_dp = in_dp;
  dst->_eta = in_eta;
}

void IDEAS_Fluid_Movers_BaseClasses_Euler_peak_copy_p(void* v_src, void* v_dst) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_peak* src = (IDEAS_Fluid_Movers_BaseClasses_Euler_peak*)(v_src);
  IDEAS_Fluid_Movers_BaseClasses_Euler_peak* dst = (IDEAS_Fluid_Movers_BaseClasses_Euler_peak*)(v_dst);
  dst->_V_flow = src->_V_flow;
  dst->_dp = src->_dp;
  dst->_eta = src->_eta;
}


#define IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc_added 1
const char* IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc__fields[3] = {"V_flow","P","d"};
struct record_description IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc = {
  "IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative", /* package_record__X */
  "IDEAS.Fluid.Movers.BaseClasses.Euler.powerWithDerivative", /* package.record_X */
  IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc__fields
};

void IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_construct_p(threadData_t *threadData, void* v_ths ) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* ths = (IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_ths);
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)11); // ths->_V_flow has no default value.
  alloc_real_array(&(ths->_P), 1, (_index_t)11); // ths->_P has no default value.
  alloc_real_array(&(ths->_d), 1, (_index_t)11); // ths->_d has no default value.
}
void IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_wrap_vars_p(threadData_t *threadData, void* v_dst , real_array in_V_flow, real_array in_P, real_array in_d) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* dst = (IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_dst);
  dst->_V_flow = in_V_flow;
  dst->_P = in_P;
  dst->_d = in_d;
}

void IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p(void* v_src, void* v_dst) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* src = (IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_src);
  IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* dst = (IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_dst);
  real_array_copy_data(src->_V_flow, dst->_V_flow);
  real_array_copy_data(src->_P, dst->_P);
  real_array_copy_data(src->_d, dst->_d);
}


#define pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.SenTempIn_cold.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_SenTempIn__cold_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


void IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_construct_p(threadData_t *threadData, void* v_ths , real_array in_V_flow, real_array in_P, real_array in_d) {
  IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* ths = (IDEAS_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_ths);
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)11);
  real_array_copy_data(in_V_flow, ths->_V_flow);
  
  alloc_real_array(&(ths->_P), 1, (_index_t)11);
  real_array_copy_data(in_P, ths->_P);
  
  alloc_real_array(&(ths->_d), 1, (_index_t)11);
  real_array_copy_data(in_d, ths->_d);
  
}

#define pump__v3__basicCold__t_bou1_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_bou1_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_bou1_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_bou1_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.bou1.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_bou1_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_bou1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_bou1_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_bou1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_bou1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_bou1_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_bou1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_bou1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_bou1_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_bou1_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_bou1_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_bou1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.del.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.heaLos_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.heaLos_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.res.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.vol_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.vol_a.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.vol_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe.vol_b.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.del.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.heaLos_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.heaLos_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.res.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.vol_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.vol_a.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.vol_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe1.vol_b.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe1_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.del.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.heaLos_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.heaLos_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.res.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.vol_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.vol_a.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.vol_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe2.vol_b.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe2_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.del.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_del_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.heaLos_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.heaLos_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_heaLos__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.res.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.vol_a.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.vol_a.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__a_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.vol_b.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.plugFlowPipe_heat.vol_b.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_plugFlowPipe__heat_vol__b_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_pump_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_pump_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_pump_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_pump_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.pump.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_pump_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_pump_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_pump_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_pump_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_pump_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_pump_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_pump_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_pump_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_pump_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_pump_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.pump.preSou.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.pump.vol.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.pump.vol.dynBal.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_pump_vol_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.senTemIn_heat.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_senTemIn__heat_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.senTemOut_cold.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_senTemOut__cold_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState__desc_added 1
const char* pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState__desc = {
  "pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState", /* package_record__X */
  "pump_v3_basicCold_t.senTemOut_heat.Medium.ThermodynamicState", /* package.record_X */
  pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState__desc__fields
};

void pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState* ths = (pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState* src = (pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState*)(v_src);
  pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState* dst = (pump__v3__basicCold__t_senTemOut__heat_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#ifdef __cplusplus
}
#endif

